export const PRODUCT_ITEM_INCREMENT = 'PRODUCT_ITEM_INCREMENT';
export const PRODUCT_ITEM_DECREMENT = 'PRODUCT_ITEM_DECREMENT';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_REMOVE = 'PRODUCT_REMOVE';